#!/bin/bash
# sync-controller-webhook.sh
#
# Fetches the controller webhook manifests from the openeverest repo
# and transforms them into Helm templates for the everest-controller component.
#
# Syncs:
#   config/webhook/service.yaml   -> templates/everest-controller/webhook.service.yaml
#   config/webhook/manifests.yaml -> templates/everest-controller/webhook.yaml
#
# Usage:
#   OPENEVEREST_REPO_URL=https://github.com/openeverest/openeverest \
#   OPENEVEREST_VERSION=v2 \
#   OUTPUT_DIR=templates/everest-controller \
#     ./scripts/sync-controller-webhook.sh
#
# This script is designed to be called by the helm-charts Makefile's
# `controller-webhook-gen` target, mirroring the `controller-manifests-gen` pattern.

set -euo pipefail

OPENEVEREST_REPO_URL="${OPENEVEREST_REPO_URL:?OPENEVEREST_REPO_URL is required}"
OPENEVEREST_VERSION="${OPENEVEREST_VERSION:?OPENEVEREST_VERSION is required}"
OUTPUT_DIR="${OUTPUT_DIR:?OUTPUT_DIR is required}"

# Convert github.com URL to raw.githubusercontent.com for direct file fetching.
RAW_BASE="${OPENEVEREST_REPO_URL/github.com/raw.githubusercontent.com}/${OPENEVEREST_VERSION}"

mkdir -p "${OUTPUT_DIR}"

echo "Fetching webhook manifests from ${OPENEVEREST_REPO_URL} @ ${OPENEVEREST_VERSION}..."

# -------------------------------------------------------------------------
# 1. Sync webhook Service
#    Source: config/webhook/service.yaml
#    Dest:   templates/everest-controller/webhook.service.yaml
# -------------------------------------------------------------------------
WEBHOOK_SERVICE_SRC="${RAW_BASE}/config/webhook/service.yaml"
WEBHOOK_SERVICE_DEST="${OUTPUT_DIR}/webhook.service.yaml"

echo "  Syncing webhook Service -> ${WEBHOOK_SERVICE_DEST}"

curl -sSfL "${WEBHOOK_SERVICE_SRC}" \
  | sed \
      -e 's|name: webhook-service|name: everest-controller-webhook-service|' \
      -e 's|namespace: system|namespace: {{ include "everest.namespace" . }}|' \
      -e '/app.kubernetes.io\/name: openeverest/d' \
      -e 's|app.kubernetes.io/managed-by: kustomize|app.kubernetes.io/managed-by: kustomize\n    app.kubernetes.io/name: everest-controller|' \
      -e 's|control-plane: controller-manager|app: everest-controller|' \
      -e 's|^    - port:|  - port:|' \
      -e 's|^      protocol:|    protocol:|' \
      -e 's|^      targetPort:|    targetPort:|' \
  | { echo '{{- if .Values.controller.enabled }}'; cat; echo '{{- end }}'; } \
  > "${WEBHOOK_SERVICE_DEST}"

# -------------------------------------------------------------------------
# 2. Sync ValidatingWebhookConfiguration
#    Source: config/webhook/manifests.yaml
#    Dest:   templates/everest-controller/webhook.yaml
#
#    The source only contains the ValidatingWebhookConfiguration.
#    We inject:
#      - Helm guard ({{- if .Values.controller.enabled }})
#      - caBundle from Helm-generated TLS cert (everestController.tlsCerts helper)
#      - TLS Secret (not present in source — generated by Helm at install time)
# -------------------------------------------------------------------------
WEBHOOK_MANIFESTS_SRC="${RAW_BASE}/config/webhook/manifests.yaml"
WEBHOOK_MANIFESTS_DEST="${OUTPUT_DIR}/webhook.yaml"

echo "  Syncing ValidatingWebhookConfiguration -> ${WEBHOOK_MANIFESTS_DEST}"

MANIFESTS_CONTENT=$(curl -sSfL "${WEBHOOK_MANIFESTS_SRC}")

# Transform the ValidatingWebhookConfiguration:
#   - Rename the webhook configuration itself
#   - Rename the service reference
#   - Template the namespace
#   - Rename the webhook admission name (kb.io -> openeverest.io)
#   - Inject caBundle after 'clientConfig:' line (Helm TLS helper)
TRANSFORMED=$(echo "${MANIFESTS_CONTENT}" \
  | sed \
      -e 's|name: validating-webhook-configuration|name: everest-controller-validating-webhook-configuration|' \
      -e 's|name: webhook-service|name: everest-controller-webhook-service|' \
      -e 's|namespace: system|namespace: {{ include "everest.namespace" . }}|' \
      -e 's|name: vmonitoringconfig-v1alpha1.kb.io|name: vmonitoringconfig-v1alpha1.monitoring.openeverest.io|' \
  | awk '/clientConfig:/{print; print "    caBundle: {{ index $tls \"ca.crt\" }}"; next}1')

# Write the full Helm template:
#   header (guard + TLS variable) + transformed content + TLS Secret + footer
cat > "${WEBHOOK_MANIFESTS_DEST}" << 'HELM_HEADER'
{{- if .Values.controller.enabled }}
{{ $tls := fromYaml (include "everestController.tlsCerts" .) }}
---
HELM_HEADER

# Strip any leading '---' from the source to avoid duplicates.
echo "${TRANSFORMED}" | sed '/^---$/d' >> "${WEBHOOK_MANIFESTS_DEST}"

cat >> "${WEBHOOK_MANIFESTS_DEST}" << 'HELM_FOOTER'
---
apiVersion: v1
kind: Secret
metadata:
  name: everest-controller-webhook-server-cert
  namespace: {{ include "everest.namespace" . }}
type: kubernetes.io/tls
data:
  {{- range $key, $value := $tls }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
HELM_FOOTER

echo ""
echo "Webhook sync complete. Files written to ${OUTPUT_DIR}/."
echo "Note: The TLS Secret and caBundle injection are Helm-specific additions"
echo "      not present in the openeverest source — do not remove them."
