{{- if .Values.upgrade.preflightChecks }}
{{- include "everest.preUpgradeChecks" (dict "namespace" (include "everest.namespace" .) "version" .Chart.AppVersion "versionMetadataURL" (include "everest.versionMetadataURL" .) "image" (.Values.hooks.upgradeChecks.image | default .Values.hooks.image)) }}
{{- end }}
